// ==================== ACTIVITY PHOTOS ====================
const activityPhotos = {
    'Times Square': 'img/activities/times_square.jpg',
    'Rockefeller': 'img/activities/rockefeller_center.jpg',
    'FAO Schwarz': 'img/activities/fao_schwarz.jpg',
    'LEGO Store': 'img/activities/lego_store_ny.jpg',
    "Joe's Pizza": 'img/activities/joes_pizza.jpg',
    'Russ & Daughters': 'img/activities/russ_and_daughters.jpg',
    "Hell's Kitchen": 'img/activities/hells_kitchen.jpg',
    'Marriott Marquis': 'img/activities/marriott_marquis.jpg',
    'St. Patrick': 'img/activities/st_patricks_cathedral.jpg',
    'Nintendo NY': 'img/activities/nintendo_ny.jpg',
    'MoMA': 'img/activities/moma.jpg',
    'Bryant Park': 'img/activities/bryant_park.jpg',
    'Biblioteca Pública': 'img/activities/biblioteca_p_blica.jpg',
    'NY Public Library': 'img/activities/ny_public_library.jpg',
    'Ghostbusters': 'img/activities/ghostbusters.jpg',
    'Charging Bull': 'img/activities/charging_bull.jpg',
    'Fearless Girl': 'img/activities/fearless_girl.jpg',
    'Trinity Church': 'img/activities/trinity_church.jpg',
    'Oculus': 'img/activities/oculus.jpg',
    '9/11 Memorial': 'img/activities/9_11_memorial.jpg',
    'One World Observatory': 'img/activities/one_world_observatory.jpg',
    '7 World Trade': 'img/activities/7_world_trade_center.jpg',
    'Brooklyn Bridge': 'img/activities/brooklyn_bridge.jpg',
    'DUMBO': 'img/activities/dumbo.jpg',
    'Brooklyn Bridge Park': 'img/activities/brooklyn_bridge_park.jpg',
    "Jane's Carousel": 'img/activities/janes_carousel.jpg',
    "Juliana's Pizza": 'img/activities/julianas_pizza.jpg',
    'Coney Island': 'img/activities/coney_island.jpg',
    "Nathan's Famous": 'img/activities/nathans_famous.jpg',
    'SoHo': 'img/activities/soho.jpg',
    'Washington Square': 'img/activities/washington_square.jpg',
    'Chelsea Market': 'img/activities/chelsea_market.jpg',
    'High Line': 'img/activities/high_line.jpg',
    'Little Island': 'img/activities/little_island.jpg',
    'Pier 57': 'img/activities/pier_57_nyc.jpg',
    'The Vessel': 'img/activities/the_vessel_nyc.jpg',
    'Hudson Yards': 'img/activities/hudson_yards.jpg',
    '5th Avenue': 'img/activities/5th_avenue.jpg',
    'Central Park': 'img/activities/central_park.jpg',
    'Strawberry Fields': 'img/activities/strawberry_fields.jpg',
    'Bethesda Fountain': 'img/activities/bethesda_fountain.jpg',
    'Bow Bridge': 'img/activities/bow_bridge.jpg',
    'MET': 'img/activities/met.jpg',
    'História Natural': 'img/activities/natural_history_museum.jpg',
    'Shake Shack': 'img/activities/shake_shack.jpg',
    "Macy's": 'img/activities/macys_herald_square.jpg',
    'Chinatown': 'img/activities/chinatown_ny.jpg',
    'Little Italy': 'img/activities/little_italy_ny.jpg',
    'Ferrara': 'img/activities/little_italy_ny.jpg',
    'Ess-a-Bagel': 'img/activities/ess_a_bagel.jpg',
    'Eataly': 'img/activities/eataly_nyc.jpg',
    'Suka Sushi': 'img/activities/suka_sushi.jpg',
    "Junior's": 'img/activities/juniors_cheesecake.jpg',
    "Carmine's": 'img/activities/juniors_cheesecake.jpg',
    'Summit One Vanderbilt': 'img/activities/summit_one_vanderbilt.jpg',
    'Grand Central Terminal': 'img/activities/grand_central_terminal.jpg',
    'General Sherman Tree': 'img/activities/general_sherman_tree.jpg',
    'Congress Trail': 'img/activities/congress_trail.jpg',
    'Kings Canyon': 'img/activities/kings_canyon.jpg',
    'Zumwalt Meadow': 'img/activities/zumwalt_meadow.jpg',
    'Roaring River Falls': 'img/activities/roaring_river_falls.jpg',
    'Crescent Meadow': 'img/activities/crescent_meadow.jpg',
    'Moro Rock': 'img/activities/moro_rock.jpg',
    'Tunnel View': 'img/activities/tunnel_view.jpg',
    'Yosemite Fall': 'img/activities/yosemite_falls_lower.jpg',
    'Swinging Bridge': 'img/activities/swinging_bridge_yosemite.jpg',
    'Valley View': 'img/activities/valley_view_yosemite.jpg',
    "Cook's Meadow": 'img/activities/cooks_meadow.jpg',
    'Vernal Fall': 'img/activities/vernal_fall.jpg',
    'Mirror Lake': 'img/activities/mirror_lake.jpg',
    'Bridalveil Fall': 'img/activities/bridalveil_fall.jpg',
    'Sentinel Bridge': 'img/activities/sentinel_bridge.jpg',
    'Yosemite Chapel': 'img/activities/yosemite_chapel.jpg',
    'Half Dome': 'img/activities/half_dome.jpg',
    'Embarcadero': 'img/activities/embarcadero_sf.jpg',
    'Crissy Field': 'img/activities/crissy_field.jpg',
    "Fisherman's Wharf": 'img/activities/fishermans_wharf.jpg',
    'Golden Gate Bridge': 'img/activities/golden_gate_bridge.jpg',
    'Pier 39': 'img/activities/pier_39.jpg',
    'Haight-Ashbury': 'img/activities/haight_ashbury.jpg',
    'Fort Point': 'img/activities/fort_point.jpg',
    'Union Square': 'img/activities/union_square_sf.jpg',
    'North Beach': 'img/activities/north_beach_sf.jpg',
    'Mission District': 'img/activities/mission_district.jpg',
    'La Taqueria': 'img/activities/la_taqueria.jpg',
    'Sausalito': 'img/activities/sausalito.jpg',
    'Muir Woods': 'img/activities/muir_woods.jpg',
    'Carson Mansion': 'img/activities/carson_mansion.jpg',
    'Lady Bird Johnson': 'img/activities/lady_bird_johnson_grove.jpg',
    'Prairie Creek': 'img/activities/prairie_creek.jpg',
    'Gold Bluffs Beach': 'img/activities/gold_bluffs_beach.jpg',
    'Newton B. Drury': 'img/activities/newton_b_drury.jpg',
    'Big Tree Wayside': 'img/activities/big_tree_wayside.jpg',
    'Stout Memorial Grove': 'img/activities/stout_memorial_grove.jpg',
    'Fern Canyon': 'img/activities/fern_canyon.jpg',
    'Cape Blanco': 'img/activities/cape_blanco.jpg',
    'Tall Trees Grove': 'img/activities/tall_trees_grove.jpg',
    'Gold Beach': 'img/activities/gold_beach_or.jpg',
    'Dean Creek': 'img/activities/dean_creek_elk.jpg',
    'Shore Acres': 'img/activities/shore_acres.jpg',
    'Ecola State Park': 'img/activities/ecola_state_park.jpg',
    'Cannon Beach': 'img/activities/cannon_beach.jpg',
    'Newport': 'img/activities/newport_oregon.jpg',
    'Haystack Rock': 'img/activities/haystack_rock.jpg',
    'Lake Crescent': 'img/activities/lake_crescent.jpg',
    'Sol Duc Falls': 'img/activities/sol_duc_falls.jpg',
    'Hoh Rain Forest': 'img/activities/hoh_rain_forest.jpg',
    'Ruby Beach': 'img/activities/ruby_beach.jpg',
    'Rialto Beach': 'img/activities/rialto_beach.jpg',
    'Marymere Falls': 'img/activities/marymere_falls.jpg',
    'Nisqually Vista': 'img/activities/nisqually_vista.jpg',
    'Mt. Rainier': 'img/activities/mt__rainier.jpg',
    'Portland': 'img/activities/portland_or.jpg',
    'Voodoo Doughnut': 'img/activities/voodoo_doughnut.jpg',
    "Powell's Books": 'img/activities/powells_books.jpg',
    'Pittock Mansion': 'img/activities/pittock_mansion.jpg',
    'Multnomah Falls': 'img/activities/multnomah_falls.jpg',
    'Boise River': 'img/activities/boise_river.jpg',
    'Idaho State Capitol': 'img/activities/idaho_state_capitol.jpg',
    'Basque Block': 'img/activities/basque_block.jpg',
    'Shoshone Falls': 'img/activities/shoshone_falls.jpg',
    'Perrine Bridge': 'img/activities/perrine_bridge.jpg',
    'Evel Knievel': 'img/activities/evel_knievel_jump_site.jpg',
    'Mesa Arch': 'img/activities/mesa_arch.jpg',
    'Upheaval Dome': 'img/activities/upheaval_dome.jpg',
    'Delicate Arch': 'img/activities/delicate_arch.jpg',
    'Balanced Rock': 'img/activities/balanced_rock.jpg',
    'Dead Horse Point': 'img/activities/dead_horse_point.jpg',
    'Red Canyon': 'img/activities/red_canyon_ut.jpg',
    'Bryce Canyon': 'img/activities/bryce_canyon.jpg',
    'Angels Landing': 'img/activities/angels_landing.jpg',
    'Grand Canyon': 'img/activities/grand_canyon.jpg',
    'Valley of Fire': 'img/activities/valley_of_fire.jpg',
    'Badwater Basin': 'img/activities/badwater_basin.jpg',
    'Red Rock Canyon': 'img/activities/red_rock_canyon.jpg',
    'Santa Monica Pier': 'img/activities/santa_monica_pier.jpg',
    'Griffith Observatory': 'img/activities/griffith_observatory.jpg',
    'Venice Beach': 'img/activities/venice_beach.jpg',
    'Welcome to Las Vegas': 'img/activities/welcome_to_las_vegas.jpg',
    'Katz\'s Deli': 'img/activities/katz_s_deli.jpg',
    'Levain Bakery': 'img/activities/levain_bakery.jpg',
    'The Plaza Hotel': 'img/activities/the_plaza_hotel.jpg',
    'Flatiron': 'img/activities/flatiron.jpg',
    'Roosevelt Island Tramway': 'img/activities/roosevelt_island_tramway.jpg',
    'General Grant': 'img/activities/general_grant.jpg',
    'El Capitan': 'img/activities/el_capitan.jpg',
    'Badger Pass': 'img/activities/badger_pass.jpg',
    'Lombard Street': 'img/activities/lombard_street.jpg',
    'Painted Ladies': 'img/activities/painted_ladies.jpg',
    'Cable Car': 'img/activities/cable_car.jpg',
    'Chinatown de SF': 'img/activities/chinatown_de_sf.jpg',
    'Point Reyes': 'img/activities/point_reyes.jpg',
    'Astoria': 'img/activities/astoria.jpg',
    'Astoria-Megler': 'img/activities/astoria_megler_bridge.jpg',
    'Forks': 'img/activities/forks_washington.jpg',
    'Hall of Mosses': 'img/activities/hall_of_mosses.jpg',
    'La Push': 'img/activities/la_push.jpg',
    'Mt. Hood': 'img/activities/mt_hood.jpg',
    'Trillium Lake': 'img/activities/trillium_lake.jpg',
    'Columbia River Gorge': 'img/activities/columbia_river_gorge.jpg',
    'Deadman Pass': 'img/activities/deadman_pass.jpg',
    'Antelope Island': 'img/activities/antelope_island.jpg',
    'Great Salt Lake': 'img/activities/great_salt_lake.jpg',
    'Grand View Point': 'img/activities/grand_view_point.jpg',
    'Green River Overlook': 'img/activities/green_river_overlook.jpg',
    'White Rim Overlook': 'img/activities/white_rim_overlook.jpg',
    'Aztec Butte': 'img/activities/aztec_butte.jpg',
    'Landscape Arch': 'img/activities/landscape_arch.jpg',
    'Double Arch': 'img/activities/double_arch.jpg',
    'Windows': 'img/activities/windows_arches.jpg',
    'Fiery Furnace': 'img/activities/fiery_furnace.jpg',
    'Park Avenue': 'img/activities/park_avenue_arches.jpg',
    'Navajo Loop': 'img/activities/navajo_loop.jpg',
    "Queen's Garden": 'img/activities/queens_garden.jpg',
    'Sunrise': 'img/activities/sunrise_point_bryce.jpg',
    'Sunset Point': 'img/activities/sunrise_point_bryce.jpg',
    'Bryce Point': 'img/activities/bryce_point.jpg',
    'Inspiration Point': 'img/activities/inspiration_point_bryce.jpg',
    'Natural Bridge': 'img/activities/natural_bridge_bryce.jpg',
    'Rainbow Point': 'img/activities/rainbow_point_bryce.jpg',
    'Riverside Walk': 'img/activities/riverside_walk_zion.jpg',
    'Canyon Overlook': 'img/activities/canyon_overlook.jpg',
    'Emerald Pools': 'img/activities/emerald_pools.jpg',
    "Pa'rus Trail": 'img/activities/parus_trail.jpg',
    'Weeping Rock': 'img/activities/weeping_rock.jpg',
    'Court of the Patriarchs': 'img/activities/court_of_patriarchs.jpg',
    'Mather Point': 'img/activities/mather_point.jpg',
    'Yavapai': 'img/activities/yavapai_point.jpg',
    'Grandview Point': 'img/activities/grandview_point.jpg',
    'Desert View Watchtower': 'img/activities/desert_view_watchtower.jpg',
    'Hopi Point': 'img/activities/hopi_point.jpg',
    'Bright Angel Trail': 'img/activities/bright_angel_trail.jpg',
    'Bellagio Fountains': 'img/activities/bellagio_fountains.jpg',
    'In-N-Out': 'img/activities/in_n_out_burger.jpg',
    'Strip': 'img/activities/las_vegas_strip_night.jpg',
    'Fire Wave': 'img/activities/fire_wave.jpg',
    'Elephant Rock': 'img/activities/elephant_rock.jpg',
    'White Domes': 'img/activities/white_domes.jpg',
    'Zabriskie Point': 'img/activities/zabriskie_point.jpg',
    "Artist's Palette": 'img/activities/artists_palette.jpg',
    'El Matador Beach': 'img/activities/el_matador_beach.jpg',
    'Malibu': 'img/activities/malibu_pch.jpg',
    'Muscle Beach': 'img/activities/muscle_beach.jpg',
    'Hollywood Sign': 'img/activities/hollywood_sign.jpg',
    'Calico Tanks': 'img/activities/calico_tanks.jpg',
    'Samuel Boardman': 'img/activities/samuel_boardman.jpg',
    'Cape Perpetua': 'img/activities/cape_perpetua.jpg',
    "Thor's Well": 'img/activities/thor_s_well.jpg',
    'Heceta Head': 'img/activities/heceta_head.jpg',
    'Natural Bridges': 'img/activities/natural_bridges.jpg',
    'Mesquite Flat Sand Dunes': 'img/activities/mesquite_flat_sand_dunes.jpg',
    "Dante's View": 'img/activities/dante_s_view.jpg',
    'Seven Magic Mountains': 'img/activities/seven_magic_mountains.jpg',
    'Watchman Trail': 'img/activities/watchman_trail.jpg',
    'Corona Arch': 'img/activities/corona_arch.jpg',
    'Scenic Byway 128': 'img/activities/scenic_byway_128.jpg',
    'Big Bend': 'img/activities/big_bend_zion.jpg',
    'Canyon Junction': 'img/activities/canyon_junction_bridge.jpg',
    'Giant Forest Museum': 'img/activities/giant_forest_museum.jpg',
    'Big Trees Trail': 'img/activities/big_trees_trail.jpg',
    'Golden Gate Park': 'img/activities/golden_gate_park.jpg',
    'Ocean Beach': 'img/activities/ocean_beach_sf.jpg',
    'Temple Square': 'img/activities/temple_square.jpg',
    'Buffalo Point': 'img/activities/buffalo_point.jpg',
    'Hermit Road': 'img/activities/hermit_road.jpg',
    // --- Additional mappings (coverage pass) ---
    'Las Vegas': 'img/activities/las_vegas_strip_night.jpg',
    'Kyle Canyon': 'img/activities/red_rock_canyon.jpg',
    'brincar na neve': 'img/activities/badger_pass.jpg',
    'Cathedral Rock Trail': 'img/activities/calico_tanks.jpg',
    'Mt. Charleston Lodge': 'img/activities/mt_charleston.jpg',
    'Death Valley': 'img/activities/zabriskie_point.jpg',
    'Springdale': 'img/activities/canyon_overlook.jpg',
    'Bryce Amphitheater': 'img/activities/bryce_canyon.jpg',
    'Stargazing': 'img/activities/bryce_point.jpg',
    'Moab': 'img/activities/corona_arch.jpg',
    'Potash Road': 'img/activities/dead_horse_point.jpg',
    'Thelma & Louise': 'img/activities/dead_horse_point.jpg',
    'SLC': 'img/activities/temple_square.jpg',
    'Boise': 'img/activities/shoshone_falls.jpg',
    'Centralia': 'img/activities/centralia_wa.jpg',
    'Henry M. Jackson': 'img/activities/mt__rainier.jpg',
    'Spruce Nature Trail': 'img/activities/hoh_rain_forest.jpg',
    'Crescent City': 'img/activities/crescent_city_ca.jpg',
    'Avenue of the Giants': 'img/activities/avenue_of_the_giants.jpg',
    'Eureka': 'img/activities/carson_mansion.jpg',
    'Nintendo San Francisco': 'img/activities/nintendo_ny.jpg',
    'San Francisco': 'img/activities/golden_gate_bridge.jpg',
    'Half Moon Bay': 'img/activities/half_moon_bay_ca.jpg',
    'Santa Cruz': 'img/activities/santa_cruz_ca.jpg',
    'Monterey': 'img/activities/monterey_ca.jpg',
    'Carmel-by-the-Sea': 'img/activities/carmel_by_the_sea.jpg',
    '17-Mile Drive': 'img/activities/17_mile_drive.jpg',
    'Bixby Creek Bridge': 'img/activities/bixby_creek_bridge.jpg',
    'Big Sur': 'img/activities/big_sur_coast.jpg',
    'Mariposa': 'img/activities/mariposa_ca.jpg',
    '1850 Restaurant': 'img/activities/mariposa_ca.jpg',
    'Majestic Yosemite': 'img/activities/majestic_yosemite_hotel.jpg',
    'Yosemite Village': 'img/activities/yosemite_village_hub.jpg',
    'Ansel Adams': 'img/activities/yosemite_village_hub.jpg',
    'Three Rivers': 'img/activities/three_rivers_ca.jpg',
    'LA': 'img/activities/griffith_observatory.jpg',
    'Santa Monica': 'img/activities/santa_monica_pier.jpg',
    // --- New route additions ---
    'Tunnel Log': 'img/activities/congress_trail.jpg',
    'Auto Log': 'img/activities/congress_trail.jpg',
    'Howland Hill Road': 'img/activities/stout_memorial_grove.jpg',
    'Boy Scout Tree Trail': 'img/activities/stout_memorial_grove.jpg',
    'Battery Point Lighthouse': 'img/activities/crescent_city_ca.jpg',
    'Del Norte Coast Redwoods': 'img/activities/newton_b_drury.jpg',
    'Damnation Creek': 'img/activities/newton_b_drury.jpg',
    'Jedediah Smith': 'img/activities/stout_memorial_grove.jpg',
    'Orick': 'img/activities/tall_trees_grove.jpg',
    'Fog Harbor': 'img/activities/fishermans_wharf.jpg',
    'Ferry Building': 'img/activities/embarcadero_sf.jpg',
    'Alcatraz': 'img/activities/alcatraz.jpg',
    'Elephant Seal Vista Point': 'img/activities/elephant_seal_vista_point.jpg',
    'Hearst Castle': 'img/activities/hearst_castle.jpg',
    'Santa Barbara': 'img/activities/santa_barbara.jpg',
    'State Street': 'img/activities/santa_barbara.jpg',
    'Santa Barbara County Courthouse': 'img/activities/santa_barbara.jpg',
    'East Beach': 'img/activities/santa_barbara.jpg',
    'Stearns Wharf': 'img/activities/stearns_wharf.jpg',
    'Point Mugu': 'img/activities/point_mugu.jpg',
    'Hollywood Walk of Fame': 'img/activities/hollywood_walk_of_fame.jpg',
    'TCL Chinese Theatre': 'img/activities/tcl_chinese_theatre.jpg',
    'The Grove': 'img/activities/the_grove_la.jpg',
    'Farmers Market': 'img/activities/the_grove_la.jpg',
    'Citadel Outlets': 'img/activities/citadel_outlets.jpg',
    'The Lark': 'img/activities/santa_barbara.jpg',
    // --- Roadside stops ---
    'Alien Fresh Jerky': 'img/activities/alien_fresh_jerky.jpg',
    'Cape Disappointment': 'img/activities/cape_disappointment.jpg',
    'Capitol Reef': 'img/activities/capitol_reef.jpg',
    'Checkerboard Mesa': 'img/activities/checkerboard_mesa.jpg',
    'Glass Beach': 'img/activities/glass_beach.jpg',
    'Goblin Valley': 'img/activities/goblin_valley.jpg',
    'Hackberry General Store': 'img/activities/hackberry_general_store.jpg',
    'Head of the Rocks': 'img/activities/head_of_the_rocks.jpg',
    'Hoover Dam': 'img/activities/hoover_dam.jpg',
    'Kalaloch': 'img/activities/kalaloch_tree_of_life.jpg',
    'Tree of Life': 'img/activities/kalaloch_tree_of_life.jpg',
    'Mendocino': 'img/activities/mendocino.jpg',
    'Navajo Bridge': 'img/activities/navajo_bridge.jpg',
    'Peter Iredale': 'img/activities/peter_iredale_shipwreck.jpg',
    'Seligman': 'img/activities/seligman_route66.jpg',
    'Tehachapi Loop': 'img/activities/tehachapi_loop.jpg',
    'Vista House': 'img/activities/vista_house.jpg',
    'Crown Point': 'img/activities/vista_house.jpg',
    'World\'s Tallest Thermometer': 'img/activities/worlds_tallest_thermometer.jpg',
    // --- Roteiro sync additions ---
    'Bottle Tree Ranch': 'img/activities/seven_magic_mountains.jpg',
    'Eldorado Canyon': 'img/activities/valley_of_fire.jpg',
    'Thousand Springs': 'img/activities/shoshone_falls.jpg',
    'Rowena Crest': 'img/activities/columbia_river_gorge.jpg',
    'Kurt Cobain': 'img/activities/cannon_beach.jpg',
    'Fort Stevens': 'img/activities/peter_iredale_shipwreck.jpg',
    'Devil\'s Punchbowl': 'img/activities/newport_oregon.jpg',
    'Elk Meadow': 'img/activities/dean_creek_elk.jpg',
    'Cypress Tree Tunnel': 'img/activities/point_reyes.jpg',
    'Pigeon Point Lighthouse': 'img/activities/heceta_head.jpg',
    'Cool Cat Collective': 'img/activities/santa_monica_pier.jpg',
    'Lake Shrine': 'img/activities/golden_gate_park.jpg',
    'California Science Center': 'img/activities/giant_forest_museum.jpg',
    'Greystone Mansion & Gardens': 'img/activities/carson_mansion.jpg',
    'Getty Center': 'img/activities/golden_gate_park.jpg',
    // --- Missing locations audit (roteiro sync) ---
    'Harry Potter Shop': 'img/activities/flatiron.jpg',
    "Devil's Golf Course": 'img/activities/badwater_basin.jpg',
    'Fairyland Point': 'img/activities/bryce_canyon.jpg',
    'Mossy Cave': 'img/activities/bryce_canyon.jpg',
    'Hickman Bridge': 'img/activities/capitol_reef.jpg',
    'San Rafael Swell': 'img/activities/capitol_reef.jpg',
    'Cannery Row': 'img/activities/monterey_ca.jpg',
    'Monterey Bay Aquarium': 'img/activities/monterey_ca.jpg',
    'Pfeiffer Beach': 'img/activities/big_sur_coast.jpg',
    'McWay Falls': 'img/activities/big_sur_coast.jpg',
    'North Grove Loop': 'img/activities/general_grant.jpg',
    'Generals Highway': 'img/activities/general_sherman_tree.jpg',
    'Universal Studios': 'img/activities/hollywood_sign.jpg',
    'Snow Summit': 'img/activities/badger_pass.jpg',
    'Alpine Slide': 'img/activities/badger_pass.jpg',
    'Castle Rock Trail': 'img/activities/badger_pass.jpg',
    'Big Bear': 'img/activities/mt_charleston.jpg',
    // --- Coverage pass 2 (full-text audit) ---
    'Mt. Charleston': 'img/activities/mt_charleston.jpg',
    'Venetian': 'img/activities/las_vegas_strip_night.jpg',
    'Caesars Palace': 'img/activities/las_vegas_strip_night.jpg',
    'Furnace Creek': 'img/activities/zabriskie_point.jpg',
    'Zion Canyon': 'img/activities/canyon_overlook.jpg',
    'Zion': 'img/activities/canyon_overlook.jpg',
    'Canyonlands': 'img/activities/mesa_arch.jpg',
    'Arches NP': 'img/activities/delicate_arch.jpg',
    'Battery Spencer': 'img/activities/golden_gate_bridge.jpg',
    'Golden Gate Overlook': 'img/activities/golden_gate_bridge.jpg',
    // --- Coverage pass 3 (missing photos) ---
    'St. Patrick': 'img/activities/st_patricks_cathedral.jpg',
    "Joe's Pizza": 'img/activities/joes_pizza.jpg',
    'Ghostbusters Firehouse': 'img/activities/ghostbusters.jpg',
    'Wall Street': 'img/activities/charging_bull.jpg',
    'Brooklyn Bridge Park': 'img/activities/brooklyn_bridge_park.jpg',
    "Juliana's Pizza": 'img/activities/julianas_pizza.jpg',
    'Los Tacos No.1': 'img/activities/la_taqueria.jpg',
    'Hudson Yards': 'img/activities/hudson_yards.jpg',
    'Ferrara Bakery': 'img/activities/levain_bakery.jpg',
    'Disney Store': 'img/activities/times_square.jpg',
    'Rockefeller Center': 'img/activities/rockefeller_center.jpg',
    'Bellagio': 'img/activities/bellagio_fountains.jpg',
    'Venetian': 'img/activities/las_vegas_strip_night.jpg',
    'Caesars Palace': 'img/activities/las_vegas_strip_night.jpg',
    'Valley of Fire': 'img/activities/valley_of_fire.jpg',
    'Artist Palette': 'img/activities/artists_palette.jpg',
    'Badwater Basin': 'img/activities/badwater_basin.jpg',
    'Canyon Overlook': 'img/activities/canyon_overlook.jpg',
    'Emerald Pools': 'img/activities/emerald_pools.jpg',
    'Bryce Canyon': 'img/activities/bryce_canyon.jpg',
    'Queen\'s Garden': 'img/activities/queens_garden.jpg',
    'Navajo Loop': 'img/activities/navajo_loop.jpg',
    'Capitol Reef': 'img/activities/capitol_reef.jpg',
    'Island in the Sky': 'img/activities/grand_view_point.jpg',
    'Delicate Arch': 'img/activities/delicate_arch.jpg',
    'Landscape Arch': 'img/activities/landscape_arch.jpg',
    'Dead Horse Point': 'img/activities/dead_horse_point.jpg',
    'Antelope Island': 'img/activities/antelope_island.jpg',
    'Evel Knievel': 'img/activities/evel_knievel_jump_site.jpg',
    'Mt. Rainier': 'img/activities/mt__rainier.jpg',
    'Paradise': 'img/activities/mt__rainier.jpg',
    'Olympic NP': 'img/activities/sol_duc_falls.jpg',
    'Hoh Rain Forest': 'img/activities/hall_of_mosses.jpg',
    'Hall of Mosses': 'img/activities/hall_of_mosses.jpg',
    'Sol Duc Falls': 'img/activities/sol_duc_falls.jpg',
    'La Push': 'img/activities/la_push.jpg',
    'Cannon Beach': 'img/activities/cannon_beach.jpg',
    'Thor\'s Well': 'img/activities/thor_s_well.jpg',
    'Heceta Head': 'img/activities/heceta_head.jpg',
    'Cape Perpetua': 'img/activities/cape_perpetua.jpg',
    'Shore Acres': 'img/activities/shore_acres.jpg',
    'Fern Canyon': 'img/activities/fern_canyon.jpg',
    'Redwood NP': 'img/activities/lady_bird_johnson_grove.jpg',
    'Stout Grove': 'img/activities/stout_memorial_grove.jpg',
    'San Francisco': 'img/activities/golden_gate_bridge.jpg',
    'Golden Gate Bridge': 'img/activities/golden_gate_bridge.jpg',
    'Crissy Field': 'img/activities/crissy_field.jpg',
    'Painted Ladies': 'img/activities/painted_ladies.jpg',
    'Cable Car': 'img/activities/cable_car.jpg',
    'Alcatraz': 'img/activities/alcatraz.jpg',
    'Lombard Street': 'img/activities/lombard_street.jpg',
    'Yosemite NP': 'img/activities/tunnel_view.jpg',
    'Half Dome': 'img/activities/half_dome.jpg',
    'Tunnel View': 'img/activities/tunnel_view.jpg',
    'Sequoia NP': 'img/activities/general_sherman_tree.jpg',
    'General Sherman': 'img/activities/general_sherman_tree.jpg',
    'Moro Rock': 'img/activities/moro_rock.jpg',
    'Kings Canyon': 'img/activities/kings_canyon.jpg',
    'Griffith Observatory': 'img/activities/griffith_observatory.jpg',
    // --- Coverage pass 4 ---
    "Katz's Deli": 'img/activities/katz_s_deli.jpg',
    "World's Tallest Thermometer": 'img/activities/worlds_tallest_thermometer.jpg',
    'Bryce': 'img/activities/bryce_canyon.jpg',
    "Cook's Meadow Loop": 'img/activities/cooks_meadow.jpg',
    "Fisherman's Wharf": 'img/activities/fishermans_wharf.jpg',
    'Time Out Market': 'img/activities/chelsea_market.jpg',
    'The Goonies': 'img/activities/astoria.jpg',
    "Devil's Punchbowl": 'img/activities/cape_perpetua.jpg',
    'Coastal Trail': 'img/activities/lady_bird_johnson_grove.jpg',
    'Jurassic Park 2': 'img/activities/fern_canyon.jpg',
    'baleias cinzentas': 'img/activities/la_push.jpg',
    'SF': 'img/activities/golden_gate_bridge.jpg',
    'Tesla Model Y': 'img/activities/hollywood_walk_of_fame.jpg',
    'Scenic Drive': 'img/activities/scenic_byway_128.jpg',
    'Disney Store': 'img/activities/times_square.jpg',
    'Artist\'s Drive': 'img/activities/artists_palette.jpg',
    "Devil's Golf Course": 'img/activities/badwater_basin.jpg',
    'Los Tacos': 'img/activities/chelsea_market.jpg',
    // --- Superchargers (fallback route photo) ---
    'Supercharger Barstow': 'img/activities/seligman_route66.jpg',
    'Supercharger Salina, UT': 'img/activities/seligman_route66.jpg',
    'Supercharger Green River, UT': 'img/activities/seligman_route66.jpg',
    'Supercharger Green River': 'img/activities/seligman_route66.jpg',
    'Supercharger Price': 'img/activities/seligman_route66.jpg',
    'Supercharger Twin Falls': 'img/activities/seligman_route66.jpg',
    'Supercharger Baker City, OR': 'img/activities/seligman_route66.jpg',
    'Supercharger Pendleton, OR': 'img/activities/seligman_route66.jpg',
    'Supercharger The Dalles, OR': 'img/activities/seligman_route66.jpg',
    'Supercharger Olympia': 'img/activities/seligman_route66.jpg',
    'Supercharger Aberdeen, WA': 'img/activities/seligman_route66.jpg',
    'Supercharger Lincoln City, OR': 'img/activities/seligman_route66.jpg',
    'Supercharger Coos Bay': 'img/activities/seligman_route66.jpg',
    'Supercharger Ukiah': 'img/activities/seligman_route66.jpg',
    'Supercharger Gilroy': 'img/activities/seligman_route66.jpg',
    'Supercharger Merced': 'img/activities/seligman_route66.jpg',
    'Supercharger Fresno': 'img/activities/seligman_route66.jpg',
    'Supercharger Bakersfield': 'img/activities/seligman_route66.jpg',
    'Supercharger San Bernardino': 'img/activities/seligman_route66.jpg',
    // --- Generic/Events ---
    'Brincar na neve!': 'img/activities/mt__rainier.jpg',
    'CARREGAR ATÉ 100%!': 'img/activities/charging_bull.jpg',
    'Tesla': 'img/activities/las_vegas_strip_night.jpg',
    // --- Roadside stops (missing mappings) ---
    'Terrible\'s Road House': 'img/activities/seligman_route66.jpg',
    'Boudin': 'img/activities/fishermans_wharf.jpg',
};

// Pre-sort keys longest-first for accurate matching (e.g., "Brooklyn Bridge Park" before "Brooklyn Bridge")
const _photoKeys = Object.keys(activityPhotos).sort((a, b) => b.length - a.length);

function findPhoto(text) {
    const clean = text.replace(/<[^>]+>/g, '');
    for (let i = 0; i < _photoKeys.length; i++) {
        if (clean.includes(_photoKeys[i])) return activityPhotos[_photoKeys[i]];
    }
    return null;
}

// Helper: convert .jpg path to .webp
function webpSrc(jpg) { return jpg.replace(/\.jpg$/, '.webp'); }
function webpSrc400(jpg) { return jpg.replace(/\.jpg$/, '-400w.webp'); }
